name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [9]
        node-version: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          pnpm-version: ${{ matrix.pnpm-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm prettier:check

      - name: Run ESLint
        run: pnpm eslint:check

      - name: Run Build
        run: pnpm build
